import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { REPORT_TYPE_LABEL } from "@/lib/reports";

export const dynamic = "force-dynamic";

export default async function SharedReport({
  params,
}: {
  params: { token: string };
}) {
  const report = await prisma.report.findUnique({
    where: { shareToken: params.token },
    include: {
      participant: true,
      organisation: true,
      generatedBy: { select: { fullName: true } },
    },
  });
  if (!report || !report.shareToken) notFound();

  const metrics = (report.metricsJson || {}) as {
    totalNotes?: number;
    notesPerGoal?: Record<string, number>;
    incidents?: number;
  };

  return (
    <main className="min-h-screen bg-ink-50">
      <header
        style={{
          backgroundColor: report.organisation.primaryColor || "#2c8a6f",
        }}
        className="text-white"
      >
        <div className="max-w-3xl mx-auto px-6 py-6">
          <div className="font-semibold text-lg">
            {report.organisation.name}
          </div>
          <div className="text-xs opacity-80">
            {[
              report.organisation.legalName,
              report.organisation.abn ? `ABN ${report.organisation.abn}` : null,
            ]
              .filter(Boolean)
              .join(" · ")}
          </div>
        </div>
      </header>
      <div className="max-w-3xl mx-auto px-6 py-8 space-y-6">
        <div>
          <div className="text-xs uppercase tracking-wide text-ink-500">
            {REPORT_TYPE_LABEL[report.type]}
          </div>
          <h1 className="text-2xl font-semibold mt-1">{report.title}</h1>
          <div className="text-sm text-ink-500">
            {report.participant.preferredName || report.participant.fullName}
            {" · "}
            {report.rangeStart.toDateString()} → {report.rangeEnd.toDateString()}
          </div>
        </div>

        <div className="card p-5">
          <h2 className="font-semibold mb-3">Period overview</h2>
          <ul className="text-sm text-ink-700 space-y-1">
            <li>Approved case notes: {metrics.totalNotes ?? 0}</li>
            <li>Incident / risk events: {metrics.incidents ?? 0}</li>
            {Object.entries(metrics.notesPerGoal ?? {}).map(([g, n]) => (
              <li key={g}>
                • {g}: {n}
              </li>
            ))}
          </ul>
        </div>

        <div className="card p-5">
          <h2 className="font-semibold mb-3">Narrative</h2>
          <div className="text-sm text-ink-800 whitespace-pre-wrap">
            {report.narrative || "—"}
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <a
            href={`/api/shared/${report.shareToken}/download?format=pdf`}
            className="btn-outline"
          >
            Download PDF
          </a>
          <a
            href={`/api/shared/${report.shareToken}/download?format=docx`}
            className="btn-outline"
          >
            Download Word (.docx)
          </a>
        </div>

        <div className="text-xs text-ink-500">
          Shared by {report.organisation.name} · Generated by{" "}
          {report.generatedBy.fullName} on{" "}
          {report.createdAt.toLocaleString()}
        </div>
      </div>
    </main>
  );
}
