import { promises as fs, createWriteStream } from "fs";
import path from "path";
import { ReportType } from "@prisma/client";
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  AlignmentType,
  TextRun,
} from "docx";
import PDFDocument from "pdfkit";

export const REPORT_TYPE_LABEL: Record<ReportType, string> = {
  MONTHLY_SUMMARY: "Monthly summary",
  PLAN_REVIEW: "Plan review report",
  ALLIED_HEALTH_UPDATE: "Allied health update",
};

export interface ReportRenderInput {
  organisation: {
    name: string;
    legalName?: string | null;
    abn?: string | null;
    address?: string | null;
    contactEmail?: string | null;
    contactPhone?: string | null;
    primaryColor?: string | null;
  };
  participantName: string;
  preferredName: string;
  type: ReportType;
  rangeStart: Date;
  rangeEnd: Date;
  narrative: string;
  metrics: {
    totalNotes: number;
    notesPerGoal: Record<string, number>;
    incidents: number;
  };
  generatedBy: string;
  generatedAt: Date;
}

async function ensureStorageDir(): Promise<string> {
  const dir = path.join(process.cwd(), "storage", "reports");
  await fs.mkdir(dir, { recursive: true });
  return dir;
}

export async function renderReportPdf(
  reportId: string,
  input: ReportRenderInput,
): Promise<string> {
  const dir = await ensureStorageDir();
  const filePath = path.join(dir, `${reportId}.pdf`);
  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56, bufferPages: true });
    const stream = createWriteStream(filePath);
    doc.pipe(stream);

    // Header band
    const accent = (input.organisation.primaryColor || "#2c8a6f").replace("#", "");
    doc
      .rect(0, 0, doc.page.width, 64)
      .fill(`#${accent}`);
    doc.fillColor("#ffffff");
    doc.font("Helvetica-Bold").fontSize(16).text(input.organisation.name, 56, 22);
    doc.font("Helvetica").fontSize(10).text(
      [
        input.organisation.legalName,
        input.organisation.abn ? `ABN ${input.organisation.abn}` : null,
      ]
        .filter(Boolean)
        .join("  ·  "),
      56,
      42,
    );

    // Body
    doc.moveDown(4);
    doc.fillColor("#171b21");
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .text(REPORT_TYPE_LABEL[input.type], { align: "left" });
    doc
      .moveDown(0.3)
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#5d6a78")
      .text(
        `${input.preferredName || input.participantName} · ${input.rangeStart.toDateString()} – ${input.rangeEnd.toDateString()}`,
      );
    doc.moveDown(1);
    doc.fillColor("#171b21").fontSize(11);

    // Metrics block
    doc.font("Helvetica-Bold").text("Period overview");
    doc.moveDown(0.3).font("Helvetica");
    doc.text(`Approved case notes: ${input.metrics.totalNotes}`);
    doc.text(`Incident / risk events: ${input.metrics.incidents}`);
    if (Object.keys(input.metrics.notesPerGoal).length) {
      doc.text("Notes per goal:");
      Object.entries(input.metrics.notesPerGoal).forEach(([g, n]) => {
        doc.text(`  • ${g}: ${n}`);
      });
    }

    doc.moveDown(0.8);
    doc.font("Helvetica-Bold").text("Narrative");
    doc.moveDown(0.3).font("Helvetica");
    input.narrative.split(/\n\n+/).forEach((para) => {
      doc.text(para.trim(), { align: "left" });
      doc.moveDown(0.6);
    });

    // Footer
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      const y = doc.page.height - 40;
      doc
        .fontSize(9)
        .fillColor("#5d6a78")
        .text(
          `${input.organisation.name} · Generated by ${input.generatedBy} on ${input.generatedAt.toLocaleString()}`,
          56,
          y,
          { width: doc.page.width - 112, align: "left" },
        );
      doc.text(`Page ${i + 1} of ${range.count}`, 56, y, {
        width: doc.page.width - 112,
        align: "right",
      });
    }

    doc.end();
    stream.on("finish", () => resolve());
    stream.on("error", reject);
  });
  return filePath;
}

export async function renderReportDocx(
  reportId: string,
  input: ReportRenderInput,
): Promise<string> {
  const dir = await ensureStorageDir();
  const filePath = path.join(dir, `${reportId}.docx`);

  const headerLine = [
    input.organisation.legalName,
    input.organisation.abn ? `ABN ${input.organisation.abn}` : null,
    input.organisation.address,
    input.organisation.contactPhone,
    input.organisation.contactEmail,
  ]
    .filter(Boolean)
    .join(" · ");

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: input.organisation.name,
                bold: true,
                size: 32,
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: headerLine, size: 18, color: "5d6a78" })],
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({ text: REPORT_TYPE_LABEL[input.type] }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `${input.preferredName || input.participantName} · ${input.rangeStart.toDateString()} – ${input.rangeEnd.toDateString()}`,
                italics: true,
                color: "5d6a78",
              }),
            ],
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            text: "Period overview",
          }),
          new Paragraph(`Approved case notes: ${input.metrics.totalNotes}`),
          new Paragraph(`Incident / risk events: ${input.metrics.incidents}`),
          ...Object.entries(input.metrics.notesPerGoal).map(
            ([g, n]) => new Paragraph(`• ${g}: ${n}`),
          ),
          new Paragraph({ text: "" }),
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            text: "Narrative",
          }),
          ...input.narrative
            .split(/\n\n+/)
            .map((p) => new Paragraph({ text: p.trim() })),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by ${input.generatedBy} on ${input.generatedAt.toLocaleString()}`,
                size: 16,
                color: "5d6a78",
                italics: true,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const buf = await Packer.toBuffer(doc);
  await fs.writeFile(filePath, buf);
  return filePath;
}
