import { Booking, Message, Trip, User } from "./types";

// Coordinates are loosely around Melbourne / Geelong / Ballarat so the demo
// has a coherent geography. Distances are computed by the matching engine.

export const SEED_USERS: User[] = [
  // ─── COMPANIONS ────────────────────────────────────────────────────────
  {
    id: "c1",
    role: "companion",
    name: "Aroha Tane",
    photo: "AT",
    bio: "Primary school teacher. Catches the 8:05 train every weekday and happy to share the trip.",
    rating: 4.9,
    ratingCount: 38,
    region: "Footscray",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    comfortAreas: ["anxiety-aware", "cognitive-support", "first-aid"],
    reviewTags: ["patient", "great communicator", "punctual"],
    joinedAt: "2024-08-12",
  },
  {
    id: "c2",
    role: "companion",
    name: "Marcus Whitfield",
    photo: "MW",
    bio: "Retired bus driver. Knows every tram in the city. Loves a chat.",
    rating: 4.7,
    ratingCount: 22,
    region: "Carlton",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    comfortAreas: ["wheelchair-assist", "vision-guide", "first-aid"],
    reviewTags: ["respectful", "calm", "reliable"],
    joinedAt: "2024-06-03",
  },
  {
    id: "c3",
    role: "companion",
    name: "Priya Ramanathan",
    photo: "PR",
    bio: "Auslan student and nursing graduate. Walks home from uni through Royal Park.",
    rating: 5.0,
    ratingCount: 17,
    region: "Parkville",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "pending" },
    comfortAreas: ["hearing-support", "aac-comfortable", "anxiety-aware", "first-aid"],
    reviewTags: ["warm", "thoughtful"],
    joinedAt: "2024-11-21",
  },
  {
    id: "c4",
    role: "companion",
    name: "Jules O'Connor",
    photo: "JO",
    bio: "Disability support worker (off the clock!). Drives Geelong to Werribee three mornings a week.",
    rating: 4.8,
    ratingCount: 41,
    region: "Geelong",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    comfortAreas: ["wheelchair-assist", "cognitive-support", "anxiety-aware", "first-aid"],
    reviewTags: ["professional", "kind", "experienced"],
    joinedAt: "2024-04-09",
  },
  {
    id: "c5",
    role: "companion",
    name: "Hamish Doyle",
    photo: "HD",
    bio: "Architect. Cycles or trams it from Brunswick to the CBD. Doesn't mind slow paces.",
    rating: 4.6,
    ratingCount: 14,
    region: "Brunswick",
    verification: { wwcc: "verified", wwdc: "pending", photoId: "verified", drivers: "verified" },
    comfortAreas: ["anxiety-aware"],
    reviewTags: ["chill", "considerate"],
    joinedAt: "2025-01-15",
  },
  {
    id: "c6",
    role: "companion",
    name: "Wendy Park",
    photo: "WP",
    bio: "Pharmacist. Walks her dog Biscuit along the Bay Trail most evenings.",
    rating: 4.9,
    ratingCount: 29,
    region: "St Kilda",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    comfortAreas: ["vision-guide", "anxiety-aware", "first-aid"],
    reviewTags: ["caring", "punctual"],
    joinedAt: "2024-09-30",
  },
  {
    id: "c7",
    role: "companion",
    name: "Daniel Achterberg",
    photo: "DA",
    bio: "Civil engineer. Train commute Ballarat → Southern Cross daily. Quiet carriage type.",
    rating: 4.5,
    ratingCount: 11,
    region: "Ballarat",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    comfortAreas: ["cognitive-support", "first-aid"],
    reviewTags: ["dependable"],
    joinedAt: "2024-12-02",
  },
  {
    id: "c8",
    role: "companion",
    name: "Lara Mehmet",
    photo: "LM",
    bio: "Speech pathology student. Trams along Sydney Road on her way to placement.",
    rating: 4.8,
    ratingCount: 19,
    region: "Coburg",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "pending" },
    comfortAreas: ["aac-comfortable", "cognitive-support", "anxiety-aware"],
    reviewTags: ["patient", "warm"],
    joinedAt: "2024-10-18",
  },

  // ─── REQUESTERS ────────────────────────────────────────────────────────
  {
    id: "r1",
    role: "requester",
    name: "Heather Lin",
    photo: "HL",
    bio: "I love the library, op shops, and not having to navigate trains alone on busy days.",
    rating: 4.9,
    ratingCount: 12,
    region: "Footscray",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 123 456",
    accessibility: {
      mobility: "ambulant",
      sensory: ["none"],
      cognitiveSupport:
        "I get overwhelmed in loud, crowded spaces. A calm voice helps.",
      anxietyTriggers:
        "Last-minute platform changes; people walking too fast.",
      communicationStyle: "verbal",
    },
    trustedContact: {
      name: "Sarah Lin",
      phone: "0412 555 901",
      relationship: "Sister",
    },
    reviewTags: ["friendly", "communicative"],
    joinedAt: "2024-09-01",
  },
  {
    id: "r2",
    role: "requester",
    name: "Sam Okafor",
    photo: "SO",
    bio: "Wheelchair user. Works in the city three days a week. Happy chatter, won't bite.",
    rating: 5.0,
    ratingCount: 6,
    region: "Werribee",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 222 117",
    accessibility: {
      mobility: "wheelchair",
      sensory: ["none"],
      cognitiveSupport: "None needed.",
      anxietyTriggers: "Stairs! Always check for step-free routes.",
      communicationStyle: "verbal",
    },
    trustedContact: {
      name: "Ade Okafor",
      phone: "0411 882 014",
      relationship: "Partner",
    },
    reviewTags: ["punctual", "great communicator"],
    joinedAt: "2024-07-22",
  },
  {
    id: "r3",
    role: "requester",
    name: "Mei Tanaka",
    photo: "MT",
    bio: "Vision impaired. Use a long cane. Studying part-time at uni.",
    rating: 4.8,
    ratingCount: 9,
    region: "Parkville",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 099 882",
    accessibility: {
      mobility: "ambulant",
      sensory: ["vision"],
      cognitiveSupport: "None.",
      anxietyTriggers: "Unannounced level changes; cyclists on shared paths.",
      communicationStyle: "verbal",
    },
    trustedContact: {
      name: "Kenji Tanaka",
      phone: "0404 663 290",
      relationship: "Father",
    },
    reviewTags: ["independent", "kind"],
    joinedAt: "2024-10-04",
  },
  {
    id: "r4",
    role: "requester",
    name: "Jordan Bellamy",
    photo: "JB",
    bio: "I use an AAC device. I love trains and going to the markets.",
    rating: 4.9,
    ratingCount: 4,
    region: "Brunswick",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 555 778",
    accessibility: {
      mobility: "ambulant",
      sensory: ["none"],
      cognitiveSupport:
        "Give me time to type. Don't finish my sentences, please.",
      anxietyTriggers: "Being rushed.",
      communicationStyle: "aac",
    },
    trustedContact: {
      name: "Casey Bellamy",
      phone: "0421 010 339",
      relationship: "Mum",
    },
    reviewTags: ["thoughtful"],
    joinedAt: "2025-02-01",
  },
  {
    id: "r5",
    role: "requester",
    name: "Theo Halloran",
    photo: "TH",
    bio: "Need a calm hand to get to my Tuesday art class.",
    rating: 4.7,
    ratingCount: 7,
    region: "Coburg",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 412 003",
    accessibility: {
      mobility: "walking-aid",
      sensory: ["hearing"],
      cognitiveSupport:
        "I lipread when I can. Face me and speak clearly, no shouting.",
      anxietyTriggers: "Crowds and sudden loud announcements.",
      communicationStyle: "written",
    },
    trustedContact: {
      name: "Megan Halloran",
      phone: "0407 221 558",
      relationship: "Sister",
    },
    reviewTags: ["polite"],
    joinedAt: "2024-12-19",
  },
  {
    id: "r6",
    role: "requester",
    name: "Anya Volkov",
    photo: "AV",
    bio: "I'm 17 and my mum sometimes books for me. Headed to TAFE in Ballarat.",
    rating: 5.0,
    ratingCount: 3,
    region: "Ballarat",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    ndisNumber: "430 880 661",
    accessibility: {
      mobility: "ambulant",
      sensory: ["none"],
      cognitiveSupport:
        "I'm autistic. I might not make eye contact — I'm still listening!",
      anxietyTriggers: "Surprises in plans.",
      communicationStyle: "verbal",
    },
    trustedContact: {
      name: "Olga Volkov",
      phone: "0419 005 552",
      relationship: "Mum",
    },
    reviewTags: ["polite", "thoughtful"],
    joinedAt: "2025-03-09",
  },

  // ─── ADMIN ─────────────────────────────────────────────────────────────
  {
    id: "a1",
    role: "admin",
    name: "Toni Alvarez",
    photo: "TA",
    bio: "Trust & safety lead.",
    rating: 5,
    ratingCount: 0,
    region: "HQ",
    verification: { wwcc: "verified", wwdc: "verified", photoId: "verified", drivers: "verified" },
    joinedAt: "2024-01-01",
  },
];

// Helper: build an ISO string offset from "today" in the demo's logical now.
const NOW = new Date("2026-05-26T07:30:00+10:00");
function offset(days: number, hours = 0, minutes = 0): string {
  const d = new Date(NOW);
  d.setDate(d.getDate() + days);
  d.setHours(d.getHours() + hours);
  d.setMinutes(d.getMinutes() + minutes);
  return d.toISOString();
}

export const SEED_TRIPS: Trip[] = [
  // ─── TRAIN TRIPS ───────────────────────────────────────────────────────
  {
    id: "t1",
    companionId: "c1",
    start: { lat: -37.7993, lng: 144.8997, label: "Footscray Station" },
    end: { lat: -37.8183, lng: 144.9525, label: "Southern Cross Station" },
    departAt: offset(0, 0, 35), // ~30 mins from now
    mode: "train",
    recurrence: { kind: "weekly" },
    capacity: 1,
    fee: 8,
    notes: "Quiet carriage. I sit near the doors at the front.",
    status: "open",
  },
  {
    id: "t2",
    companionId: "c7",
    start: { lat: -37.5622, lng: 143.8503, label: "Ballarat Station" },
    end: { lat: -37.8183, lng: 144.9525, label: "Southern Cross Station" },
    departAt: offset(1, 1, 0),
    mode: "train",
    recurrence: { kind: "daily" },
    capacity: 2,
    fee: 10,
    notes: "Direct service. I bring a book; happy to chat too.",
    status: "open",
  },
  {
    id: "t3",
    companionId: "c1",
    start: { lat: -37.7993, lng: 144.8997, label: "Footscray Station" },
    end: { lat: -37.8126, lng: 144.9544, label: "Flinders Street Station" },
    departAt: offset(2, 0, 35),
    mode: "train",
    recurrence: { kind: "weekly" },
    capacity: 1,
    fee: 8,
    status: "open",
  },

  // ─── TRAM TRIPS ────────────────────────────────────────────────────────
  {
    id: "t4",
    companionId: "c8",
    start: { lat: -37.7461, lng: 144.9619, label: "Coburg, Sydney Rd & Bell St" },
    end: { lat: -37.8126, lng: 144.9544, label: "Flinders Street" },
    departAt: offset(0, 1, 0),
    mode: "tram",
    recurrence: { kind: "specific-days", days: [1, 3, 5] },
    capacity: 1,
    fee: 6,
    notes: "Route 19. I get on at Bell St.",
    status: "open",
  },
  {
    id: "t5",
    companionId: "c5",
    start: { lat: -37.7672, lng: 144.9603, label: "Brunswick, Sydney Rd" },
    end: { lat: -37.8136, lng: 144.9631, label: "Melbourne CBD" },
    departAt: offset(1, 0, 20),
    mode: "tram",
    recurrence: { kind: "daily" },
    capacity: 1,
    fee: 6,
    status: "open",
  },
  {
    id: "t6",
    companionId: "c2",
    start: { lat: -37.7993, lng: 144.9676, label: "Carlton, Lygon St" },
    end: { lat: -37.8136, lng: 144.9631, label: "Melbourne CBD" },
    departAt: offset(0, 2, 0),
    mode: "tram",
    recurrence: { kind: "weekly" },
    capacity: 2,
    fee: 5,
    status: "open",
  },

  // ─── BUS TRIPS ─────────────────────────────────────────────────────────
  {
    id: "t7",
    companionId: "c4",
    start: { lat: -38.1499, lng: 144.3617, label: "Geelong CBD" },
    end: { lat: -37.8993, lng: 144.6627, label: "Werribee Station" },
    departAt: offset(0, 0, 90),
    mode: "bus",
    recurrence: { kind: "specific-days", days: [1, 3, 5] },
    capacity: 2,
    fee: 9,
    status: "open",
  },

  // ─── CAR TRIPS ─────────────────────────────────────────────────────────
  {
    id: "t8",
    companionId: "c4",
    start: { lat: -38.1499, lng: 144.3617, label: "Geelong CBD" },
    end: { lat: -37.8993, lng: 144.6627, label: "Werribee, Pacific Drive" },
    departAt: offset(2, 0, 0),
    mode: "car",
    recurrence: { kind: "specific-days", days: [1, 3, 5] },
    capacity: 1,
    fee: 22,
    notes: "Wheelchair-accessible vehicle. ~55km.",
    status: "open",
  },
  {
    id: "t9",
    companionId: "c2",
    start: { lat: -37.7993, lng: 144.9676, label: "Carlton, Lygon St" },
    end: { lat: -37.8225, lng: 144.9921, label: "East Melbourne, Wellington Pde" },
    departAt: offset(0, 3, 0),
    mode: "car",
    recurrence: { kind: "one-off" },
    capacity: 2,
    fee: 12,
    notes: "Hospital drop-off run.",
    status: "open",
  },
  {
    id: "t10",
    companionId: "c5",
    start: { lat: -37.7672, lng: 144.9603, label: "Brunswick" },
    end: { lat: -37.8525, lng: 144.9921, label: "Richmond" },
    departAt: offset(3, 0, 0),
    mode: "car",
    recurrence: { kind: "one-off" },
    capacity: 1,
    fee: 15,
    status: "open",
  },

  // ─── WALKING TRIPS ─────────────────────────────────────────────────────
  {
    id: "t11",
    companionId: "c3",
    start: { lat: -37.7929, lng: 144.9614, label: "Royal Park, Parkville" },
    end: { lat: -37.7995, lng: 144.9555, label: "Royal Melbourne Hospital" },
    departAt: offset(0, 2, 0),
    mode: "walking",
    recurrence: { kind: "weekly" },
    capacity: 1,
    fee: 4,
    notes: "Quiet, well-paved route.",
    status: "open",
  },
  {
    id: "t12",
    companionId: "c6",
    start: { lat: -37.8676, lng: 144.9772, label: "St Kilda, Acland St" },
    end: { lat: -37.8552, lng: 144.9602, label: "Albert Park Lake" },
    departAt: offset(0, 4, 0),
    mode: "walking",
    recurrence: { kind: "daily" },
    capacity: 2,
    fee: 5,
    status: "open",
  },
  {
    id: "t13",
    companionId: "c6",
    start: { lat: -37.8676, lng: 144.9772, label: "St Kilda Beach" },
    end: { lat: -37.8552, lng: 144.9602, label: "Albert Park Lake" },
    departAt: offset(1, 4, 0),
    mode: "walking",
    recurrence: { kind: "daily" },
    capacity: 1,
    fee: 5,
    status: "open",
  },
  {
    id: "t14",
    companionId: "c3",
    start: { lat: -37.7995, lng: 144.9555, label: "RMH, Parkville" },
    end: { lat: -37.8136, lng: 144.9631, label: "Melbourne Central" },
    departAt: offset(2, -1, 0),
    mode: "walking",
    recurrence: { kind: "weekly" },
    capacity: 1,
    fee: 4,
    status: "open",
  },
  {
    id: "t15",
    companionId: "c8",
    start: { lat: -37.7461, lng: 144.9619, label: "Coburg Library" },
    end: { lat: -37.7672, lng: 144.9603, label: "Brunswick Town Hall" },
    departAt: offset(3, 1, 0),
    mode: "walking",
    recurrence: { kind: "one-off" },
    capacity: 1,
    fee: 3,
    notes: "Picking up art supplies on the way — happy to wait.",
    status: "open",
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "b1",
    tripId: "t1",
    requesterId: "r1",
    companionId: "c1",
    status: "confirmed",
    pickupOverlapKm: 0.4,
    routeOverlapKm: 6.2,
    matchScore: 94,
    paidHeldInEscrow: true,
    ratings: [],
  },
  {
    id: "b2",
    tripId: "t8",
    requesterId: "r2",
    companionId: "c4",
    status: "rated",
    pickupOverlapKm: 0.2,
    routeOverlapKm: 55,
    matchScore: 97,
    paidHeldInEscrow: false,
    startedAt: offset(-7, 0, 0),
    endedAt: offset(-7, 1, 10),
    ratings: [
      {
        by: "r2",
        stars: 5,
        comment: "Jules was wonderful — checked the ramp ahead of time. Felt safe the whole way.",
        tags: ["respectful", "punctual", "great communicator"],
        at: offset(-7, 1, 30),
      },
      {
        by: "c4",
        stars: 5,
        comment: "Sam was a delight. We did the crossword.",
        tags: ["punctual", "friendly"],
        at: offset(-7, 1, 35),
      },
    ],
  },
  {
    id: "b3",
    tripId: "t12",
    requesterId: "r6",
    companionId: "c6",
    status: "completed",
    pickupOverlapKm: 0.1,
    routeOverlapKm: 1.8,
    matchScore: 88,
    paidHeldInEscrow: false,
    startedAt: offset(-2, 0, 0),
    endedAt: offset(-2, 0, 35),
    ratings: [],
  },
];

export const SEED_MESSAGES: Message[] = [
  {
    id: "m1",
    bookingId: "b1",
    fromId: "c1",
    body: "Hi Heather! I'll be at the front-end of platform 2 in a navy coat. See you at 8:00.",
    at: offset(-1, 0, 0),
  },
  {
    id: "m2",
    bookingId: "b1",
    fromId: "r1",
    body: "Thanks Aroha! I'll wave. Wearing yellow scarf.",
    at: offset(-1, 0, 5),
  },
  {
    id: "m3",
    bookingId: "b2",
    fromId: "c4",
    body: "All set — I'll pick you up at 7:45. Ramp checked.",
    at: offset(-7, -1, 0),
  },
];

export const QUICK_REPLIES = [
  "Running 5 mins late",
  "I'm here",
  "On the platform",
  "Need to cancel — sorry",
  "All good, see you soon",
];

export const REVIEW_TAGS = [
  "punctual",
  "respectful",
  "great communicator",
  "patient",
  "warm",
  "calm",
  "reliable",
  "friendly",
  "thoughtful",
];
